fs: 22050
batch_size: 8
num_epochs: 150
early_stopping: 15
lr: 0.0001
weight_decay: 0.0001
loss: weighted_CCE
seed: 1234
training: True
optimizer: 'Adam'
amsgrad: 1
win_len: 5

#model-related
model:
  nb_samp: 64600
  first_conv: 1024   # no. of filter coefficients
  in_channels: 1
  filts: [20, [20, 20], [20, 128], [128, 128]] # no. of filters channel in residual blocks
  blocks: [2, 4]
  nb_fc_node: 1024
  gru_node: 1024
  nb_gru_layer: 3
  nb_classes: 2